-- require("ibl").setup {
--   debounce = 100,
--   indent = { char = '|' },
--   scope = {
--     show_start = false,
--     show_end = false,
--     highlight = { 'Function', 'Label' },
--   }
-- }
