listener {
  timeout = 600 # Seconds = 10 Minutes
  on-timeout = swaylock -i ~/.config/wallpaper/Sonoma-Dark.png --clock --indicator --indicator-radius 100 --effect-blur 10x5 --fade-in 1 --ring-color 608B4E --text-color ffffff
}
